### ISSUE TITLE
hi , jadeblaquiere , ask you a  pypbc question ?

### ISSUE THREAD

**Issue by zzbin2000** [jadeblaquiere/ctclient#1]
I use pypbc software . However, during use, there is a problem:

How does the void element_to_mpz(mpz_t z, element_t e) function in PBC be implemented in pypbc?

If I need to convert the element in G1 to integer z and multiply it with another element in G1, how do we achieve this? ?

I see that you have added the GetItem method, which seems to be unusable. Can it solve the problem raised above? How to use the getitem method ?

**Comment by jadeblaquiere** [comment]
This question is off-topic here but then again you can't really open an issue in my fork of the pypbc code. 

I'll start with the easy question first. I put together a short example illustrating the use of GetItem (which allows you to index the x,y coordinates of a point:

```
#! /usr/bin/env python3

from pypbc import *

if __name__ == '__main__':
	params = Parameters(qbits=8, rbits=4)
	#print("params =", str(params))
	pairing = Pairing(params)
	#print("pairing =", str(pairing))
	P = Element.random(pairing, G1)
	print("P =", str(P))
	print("P[0] = %d" % (P[0]))
	print("P[1] = %d" % (P[1]))
	Q = Element.random(pairing, G2)
	print("Q =", str(Q))
	print("P[0] = %d" % (Q[0]))
	print("P[1] = %d" % (Q[1]))
	e = pairing.apply(P, Q)
	print("len(e) =", len(e))
	print("e[0] = %d" % (e[0]))
	print("e[1] = %d" % (e[1]))
```

The output should be something like:

```
P = 0237
P[0] = 55
P[1] = 86
Q = 0331
P[0] = 49
P[1] = 45
len(e) = 2
e[0] = 85
e[1] = 80
```

Showing P is the point at (55, 86) and Q is the point at (49, 45). 

The problem of calculating the product of P and Q is that G1 is an additive group. P+Q is defined, but P*Q is not. You can mulitply either P or Q by a scalar but you cannot directly multiply two points. 

Having said that, the pairing operation e(P,Q) is somewhat similar to a "product' of the two points. So as long as you have a symmetric pairing (one which G1 and G2 are equivalent) then you can combine any two points from G1 via pairing. As the pairing is a bilinear map it has similar mathematical properties to a product (i.e. e(aP, Q) = e(P, aQ) for any scalar a. 

As far as the element_to_mpz() function goes, I haven't found that particular API necessary or even generally useful. I vaguely recall it may only actually defined for cases where e is a scalar (member of Zr).
